name: React CI
on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Tests
        # Si no tienes tests, puedes dejar --if-present para que no falle
        run: npm test --if-present -- --watchAll=false

      - name: Build
        run: npm run build
